spring:
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://192.168.3.175:3306/webadmin?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      test-while-idle: true
      test-on-return: false
      validation-query:  SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      initial-size: 5
      max-total: 50
      max-wait-millis: 6000
      min-idle: 5
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    static-path-pattern: /static/**
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点

server:
  port: 8081

logging:
  config: classpath:conf/logback.xml

